[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "ie_bike_model"
author = "Kathleen Hess"
home-page = "https://kathhess.github.io"
classifiers = [ "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",]
requires = [
    "numpy==1.20.3",
    "pandas==1.2.4",
    "joblib==1.0.1",
    "pytest==6.2.4",
    "scikit_learn==0.24.2"
]